# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: boardmessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='boardmessage.proto',
  package='aiconnector',
  syntax='proto3',
  serialized_pb=_b('\n\x12\x62oardmessage.proto\x12\x0b\x61iconnector\"\xf2\x01\n\x0c\x42oardMessage\x12:\n\x0brequesttype\x18\x01 \x01(\x0e\x32%.aiconnector.BoardMessage.RequestType\x12<\n\x0cresponsetype\x18\x02 \x01(\x0e\x32&.aiconnector.BoardMessage.ResponseType\x12\r\n\x05\x62oard\x18\x03 \x01(\t\"+\n\x0bRequestType\x12\r\n\tGET_BOARD\x10\x00\x12\r\n\tSET_BOARD\x10\x01\",\n\x0cResponseType\x12\t\n\x05\x42OARD\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BOARDMESSAGE_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='aiconnector.BoardMessage.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET_BOARD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_BOARD', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=189,
  serialized_end=232,
)
_sym_db.RegisterEnumDescriptor(_BOARDMESSAGE_REQUESTTYPE)

_BOARDMESSAGE_RESPONSETYPE = _descriptor.EnumDescriptor(
  name='ResponseType',
  full_name='aiconnector.BoardMessage.ResponseType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BOARD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=234,
  serialized_end=278,
)
_sym_db.RegisterEnumDescriptor(_BOARDMESSAGE_RESPONSETYPE)


_BOARDMESSAGE = _descriptor.Descriptor(
  name='BoardMessage',
  full_name='aiconnector.BoardMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requesttype', full_name='aiconnector.BoardMessage.requesttype', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responsetype', full_name='aiconnector.BoardMessage.responsetype', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='board', full_name='aiconnector.BoardMessage.board', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BOARDMESSAGE_REQUESTTYPE,
    _BOARDMESSAGE_RESPONSETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=278,
)

_BOARDMESSAGE.fields_by_name['requesttype'].enum_type = _BOARDMESSAGE_REQUESTTYPE
_BOARDMESSAGE.fields_by_name['responsetype'].enum_type = _BOARDMESSAGE_RESPONSETYPE
_BOARDMESSAGE_REQUESTTYPE.containing_type = _BOARDMESSAGE
_BOARDMESSAGE_RESPONSETYPE.containing_type = _BOARDMESSAGE
DESCRIPTOR.message_types_by_name['BoardMessage'] = _BOARDMESSAGE

BoardMessage = _reflection.GeneratedProtocolMessageType('BoardMessage', (_message.Message,), dict(
  DESCRIPTOR = _BOARDMESSAGE,
  __module__ = 'boardmessage_pb2'
  # @@protoc_insertion_point(class_scope:aiconnector.BoardMessage)
  ))
_sym_db.RegisterMessage(BoardMessage)


# @@protoc_insertion_point(module_scope)
