# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movemessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='movemessage.proto',
  package='aiconnector',
  syntax='proto3',
  serialized_pb=_b('\n\x11movemessage.proto\x12\x0b\x61iconnector\"\x8a\x01\n\x04Move\x12)\n\x08newpiece\x18\x01 \x01(\x0b\x32\x17.aiconnector.Move.Piece\x12.\n\rremovedpieces\x18\x02 \x03(\x0b\x32\x17.aiconnector.Move.Piece\x1a\'\n\x05Piece\x12\x0c\n\x04type\x18\x01 \x01(\x0c\x12\x10\n\x08location\x18\x02 \x01(\x05\"\xfe\x01\n\x0bMoveMessage\x12\x39\n\x0brequesttype\x18\x01 \x01(\x0e\x32$.aiconnector.MoveMessage.RequestType\x12;\n\x0cresponsetype\x18\x02 \x01(\x0e\x32%.aiconnector.MoveMessage.ResponseType\x12\x1f\n\x04move\x18\x03 \x01(\x0b\x32\x11.aiconnector.Move\")\n\x0bRequestType\x12\x0c\n\x08GET_MOVE\x10\x00\x12\x0c\n\x08SET_MOVE\x10\x01\"+\n\x0cResponseType\x12\x08\n\x04MOVE\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MOVEMESSAGE_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='aiconnector.MoveMessage.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET_MOVE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_MOVE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=344,
  serialized_end=385,
)
_sym_db.RegisterEnumDescriptor(_MOVEMESSAGE_REQUESTTYPE)

_MOVEMESSAGE_RESPONSETYPE = _descriptor.EnumDescriptor(
  name='ResponseType',
  full_name='aiconnector.MoveMessage.ResponseType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOVE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=387,
  serialized_end=430,
)
_sym_db.RegisterEnumDescriptor(_MOVEMESSAGE_RESPONSETYPE)


_MOVE_PIECE = _descriptor.Descriptor(
  name='Piece',
  full_name='aiconnector.Move.Piece',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='aiconnector.Move.Piece.type', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='aiconnector.Move.Piece.location', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=173,
)

_MOVE = _descriptor.Descriptor(
  name='Move',
  full_name='aiconnector.Move',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='newpiece', full_name='aiconnector.Move.newpiece', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='removedpieces', full_name='aiconnector.Move.removedpieces', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MOVE_PIECE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=173,
)


_MOVEMESSAGE = _descriptor.Descriptor(
  name='MoveMessage',
  full_name='aiconnector.MoveMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requesttype', full_name='aiconnector.MoveMessage.requesttype', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responsetype', full_name='aiconnector.MoveMessage.responsetype', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='move', full_name='aiconnector.MoveMessage.move', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MOVEMESSAGE_REQUESTTYPE,
    _MOVEMESSAGE_RESPONSETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=430,
)

_MOVE_PIECE.containing_type = _MOVE
_MOVE.fields_by_name['newpiece'].message_type = _MOVE_PIECE
_MOVE.fields_by_name['removedpieces'].message_type = _MOVE_PIECE
_MOVEMESSAGE.fields_by_name['requesttype'].enum_type = _MOVEMESSAGE_REQUESTTYPE
_MOVEMESSAGE.fields_by_name['responsetype'].enum_type = _MOVEMESSAGE_RESPONSETYPE
_MOVEMESSAGE.fields_by_name['move'].message_type = _MOVE
_MOVEMESSAGE_REQUESTTYPE.containing_type = _MOVEMESSAGE
_MOVEMESSAGE_RESPONSETYPE.containing_type = _MOVEMESSAGE
DESCRIPTOR.message_types_by_name['Move'] = _MOVE
DESCRIPTOR.message_types_by_name['MoveMessage'] = _MOVEMESSAGE

Move = _reflection.GeneratedProtocolMessageType('Move', (_message.Message,), dict(

  Piece = _reflection.GeneratedProtocolMessageType('Piece', (_message.Message,), dict(
    DESCRIPTOR = _MOVE_PIECE,
    __module__ = 'movemessage_pb2'
    # @@protoc_insertion_point(class_scope:aiconnector.Move.Piece)
    ))
  ,
  DESCRIPTOR = _MOVE,
  __module__ = 'movemessage_pb2'
  # @@protoc_insertion_point(class_scope:aiconnector.Move)
  ))
_sym_db.RegisterMessage(Move)
_sym_db.RegisterMessage(Move.Piece)

MoveMessage = _reflection.GeneratedProtocolMessageType('MoveMessage', (_message.Message,), dict(
  DESCRIPTOR = _MOVEMESSAGE,
  __module__ = 'movemessage_pb2'
  # @@protoc_insertion_point(class_scope:aiconnector.MoveMessage)
  ))
_sym_db.RegisterMessage(MoveMessage)


# @@protoc_insertion_point(module_scope)
