# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movemessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='movemessage.proto',
  package='aiconnector',
  syntax='proto3',
  serialized_pb=_b('\n\x11movemessage.proto\x12\x0b\x61iconnector\"\xa0\x02\n\x0bMoveMessage\x12\x39\n\x0brequesttype\x18\x01 \x01(\x0e\x32$.aiconnector.MoveMessage.RequestType\x12;\n\x0cresponsetype\x18\x02 \x01(\x0e\x32%.aiconnector.MoveMessage.ResponseType\x12+\n\x04move\x18\x03 \x01(\x0b\x32\x1d.aiconnector.MoveMessage.Move\x1a\x14\n\x04Move\x12\x0c\n\x04name\x18\x01 \x01(\t\")\n\x0bRequestType\x12\x0c\n\x08GET_MOVE\x10\x00\x12\x0c\n\x08SET_MOVE\x10\x01\"+\n\x0cResponseType\x12\x08\n\x04MOVE\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MOVEMESSAGE_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='aiconnector.MoveMessage.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET_MOVE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_MOVE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=237,
  serialized_end=278,
)
_sym_db.RegisterEnumDescriptor(_MOVEMESSAGE_REQUESTTYPE)

_MOVEMESSAGE_RESPONSETYPE = _descriptor.EnumDescriptor(
  name='ResponseType',
  full_name='aiconnector.MoveMessage.ResponseType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOVE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=280,
  serialized_end=323,
)
_sym_db.RegisterEnumDescriptor(_MOVEMESSAGE_RESPONSETYPE)


_MOVEMESSAGE_MOVE = _descriptor.Descriptor(
  name='Move',
  full_name='aiconnector.MoveMessage.Move',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='aiconnector.MoveMessage.Move.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=235,
)

_MOVEMESSAGE = _descriptor.Descriptor(
  name='MoveMessage',
  full_name='aiconnector.MoveMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requesttype', full_name='aiconnector.MoveMessage.requesttype', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responsetype', full_name='aiconnector.MoveMessage.responsetype', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='move', full_name='aiconnector.MoveMessage.move', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MOVEMESSAGE_MOVE, ],
  enum_types=[
    _MOVEMESSAGE_REQUESTTYPE,
    _MOVEMESSAGE_RESPONSETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=323,
)

_MOVEMESSAGE_MOVE.containing_type = _MOVEMESSAGE
_MOVEMESSAGE.fields_by_name['requesttype'].enum_type = _MOVEMESSAGE_REQUESTTYPE
_MOVEMESSAGE.fields_by_name['responsetype'].enum_type = _MOVEMESSAGE_RESPONSETYPE
_MOVEMESSAGE.fields_by_name['move'].message_type = _MOVEMESSAGE_MOVE
_MOVEMESSAGE_REQUESTTYPE.containing_type = _MOVEMESSAGE
_MOVEMESSAGE_RESPONSETYPE.containing_type = _MOVEMESSAGE
DESCRIPTOR.message_types_by_name['MoveMessage'] = _MOVEMESSAGE

MoveMessage = _reflection.GeneratedProtocolMessageType('MoveMessage', (_message.Message,), dict(

  Move = _reflection.GeneratedProtocolMessageType('Move', (_message.Message,), dict(
    DESCRIPTOR = _MOVEMESSAGE_MOVE,
    __module__ = 'movemessage_pb2'
    # @@protoc_insertion_point(class_scope:aiconnector.MoveMessage.Move)
    ))
  ,
  DESCRIPTOR = _MOVEMESSAGE,
  __module__ = 'movemessage_pb2'
  # @@protoc_insertion_point(class_scope:aiconnector.MoveMessage)
  ))
_sym_db.RegisterMessage(MoveMessage)
_sym_db.RegisterMessage(MoveMessage.Move)


# @@protoc_insertion_point(module_scope)
